# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-08-26 06:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dday', '0002_auto_20180826_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='finish',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='post',
            name='start',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
