# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-08-26 08:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dday', '0003_auto_20180826_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('success', '\uc721\uad70'), ('primary', '\ud574\uad70'), ('info', '\uacf5\uad70'), ('danger', '\ud574\ubcd1\ub300')], default='army', max_length=10),
        ),
    ]
