# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-09-07 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dday', '0005_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='name',
            field=models.CharField(max_length=5),
        ),
    ]
